name: terraform-dev

on:
  push:
    branches: [ "main" ]
    paths:
      - "infra/terraform/**"
      - ".github/workflows/terraform-dev.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "infra/terraform/**"
      - ".github/workflows/terraform-dev.yml"

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: infra/terraform/envs/dev

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::398265530653:role/nyc-gov-gha-terraform
          aws-region: us-east-2

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - run: terraform init -input=false
      - run: terraform fmt -check -recursive
      - run: terraform validate
      - run: terraform plan -input=false -no-color

  apply:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: infra/terraform/envs/dev

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::398265530653:role/nyc-gov-gha-terraform
          aws-region: us-east-2

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - run: terraform init -input=false
      - run: terraform apply -auto-approve -input=false